# Generated by Django 3.1 on 2020-08-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='answer text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.ForeignKey(limit_choices_to=models.Q(questions__lte=10), on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.story', verbose_name='story'),
        ),
    ]
