# Generated by Django 3.1 on 2020-08-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200828_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.ForeignKey(limit_choices_to=models.Q(_negated=True, questions__gte=10), on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.story', verbose_name='story'),
        ),
    ]
