# Generated by Django 3.1 on 2020-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200828_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='instruction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
