# Generated by Django 3.1 on 2020-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20200829_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='question content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='instruction',
            field=models.TextField(),
        ),
    ]
