# Generated by Django 3.1 on 2020-08-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200829_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.story', verbose_name='story'),
        ),
    ]
